version: '3.8'
services:
  frontend:
    image: nxhop/aws_front_test:testing1.001
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_BASE_URL=http://localhost:8002
    ports:
      - 8080:8080