version: '3.8'
services:
  frontend:
    image: rszim/aws_front:testing
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_BASE_URL=http://localhost:8002
    ports:
      - 8080:8080